config/routes.rb
Demo::Application.routes.draw do
  get "say/hello"
  get "say/goodbye"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  	wakeTime = @time.change(day: Time.now.day + 1, hour: 6, min:50)
  	@minutesUntilEndOfDay = @time.hour > 0 && @time.hour < wakeTime.hour ? 0 : Time.now.seconds_until_end_of_day / 60  	
  	@hourDifference = (@minutesUntilEndOfDay + ((wakeTime.hour * 60) + wakeTime.min)) / 60
  	@minDifference = (@minutesUntilEndOfDay + ((wakeTime.hour * 60) + wakeTime.min)) - @hourDifference * 60
  	@hourEight = (@minutesUntilEndOfDay + ((wakeTime.hour * 60) + wakeTime.min)) / 60
  	@count ||= 0;

  	if @hourDifference < 10
  		@hourDifference = "0" + @hourDifference.to_s
  	end
  	if @minDifference < 10
  		@minDifference = "0" + @minDifference.to_s
  	end

  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>
	Look at the time, 
	Its time to say <%= link_to "Hello", say_hello_path %>!
</p>

app/views/say/hello.html.erb
<head>
<script type="text/JavaScript">
	function timedRefresh(timeoutPeriod){
		setTimeout("location.reload(true);", timeoutPeriod);
		$('#totalRefresh').html(totalRefresh);
	}
</script>
</head>
<body onload="JavaScript:timedRefresh(30000);">
<h1>Who Needs Sleep?</h1>
<p>
	<div class="timeLabel hour">
		<%= @hourDifference %>
	</div>  
	<div class="timeLabel min">
		<%= @minDifference %>
	</div> 
	<div id="totalRefresh">
		<%= @count %>
	</div>
</p>
</body>